1차 리뷰 요청합니다
2Jin1031/java-lotto pull request #1
Opened 2024-04-07 11:10 UTC by 2Jin1031

2024-04-07 12:21 UTC, 3Juhwan requested changes
이진님, 안녕하세요. 코드 잘 읽었어요! 

패키지 분리한 것이 인상 깊은 코드였어요. 코드를 읽으며 패키지를 분리한 의도가 궁금했어요. 질문하고 싶은 마음이 크지만, 이 부분은 일단 넘어갈게요. 

리뷰를 하며 중점을 둔 부분은 전반적인 포맷이에요. 코드 리뷰가 처음이니까, 차근차근 진행해 보려고 해요. 몇 가지 질문도 남겼으니 확인해 주세요! 15개 내외로 남긴다고 했는데, 하다 보니 많아졌네요 :) 

아, 그리고 변경 요청드린 부분을 반영하면서 커밋을 추가하게 될 텐데요. 커밋 단위를 현재보다 세세하게 하면 좋을 것 같아요. 하나의 커밋에 많은 변경 사항이 있으면 코드 추적이 쉽지 않답니다 😉 커밋 메시지에 prefix 잘 적용하고 계시네요 👍 세부 커밋 메시지를 영어로 작성했는데 의도가 있을까요?  

코멘트 확인 부탁드리고, 2차 리뷰 요청 마감 기한은 4/10(수)에요!

2024-04-07 12:21 UTC, 3Juhwan commented on src/main/java/lotto/IO/domain/Lotto.java
> +import java.util.stream.Collectors;
사용하지 않는 클래스를 import하네요! 인텔리제이 단축키를 사용해서 지울 수 있어요. `Command+Option+L`을 눌러서 표준에 맞도록 수정해 볼까요?

2024-04-07 12:21 UTC, 3Juhwan commented on src/main/java/lotto/IO/domain/Lotto.java
> +
`validate()`는 인스턴스 메서드, `numbersRangeCheck()`는 정적 메서드로 작성해 주셨네요! 두 메서드에 다른 키워드를 붙여주신 의도가 무엇인가요?

2024-04-07 12:21 UTC, 3Juhwan commented on src/main/java/lotto/IO/domain/Quantity.java
> +    private static void validateAmooutInThousandUnites(int number) {
오타가 있네요!

2024-04-07 12:21 UTC, 3Juhwan commented on src/main/java/lotto/IO/info/Info.java
> +    }
사용하지 않는 메서드는 지우는 것이 좋아요!

2024-04-07 12:21 UTC, 3Juhwan commented on src/main/java/lotto/IO/input/Bonus.java
> +
불필요한 개행인 것 같네요. 지워볼까요?

2024-04-07 12:21 UTC, 3Juhwan commented on src/main/java/lotto/IO/input/Bonus.java
> +    private static void duplicatedwithLotto(int bonus, Lotto lotto) {
자바 메서드 명명 규칙을 찾아보고 적용해 주세요! 
https://tecoble.techcourse.co.kr/post/2020-04-26-Method-Naming/

2024-04-07 12:21 UTC, 3Juhwan commented on src/main/java/lotto/IO/input/Bonus.java
> +    public int getBonus() {
이 부분만 개행이 2줄이네요! 일관성을 위해 한 줄로 줄이는 것이 좋을 것 같아요.

2024-04-07 12:21 UTC, 3Juhwan commented on src/main/java/lotto/IO/input/InputConfig.java
> +        return input;
```suggestion
        return Console.readLine();
```

2024-04-07 12:21 UTC, 3Juhwan commented on src/main/java/lotto/IO/input/InputHandler.java
> +//import camp.nextstep.edu.missionutils.Console;
이 주석은 지우는 것이 좋아요!

2024-04-07 12:21 UTC, 3Juhwan commented on src/main/java/lotto/IO/input/InputHandler.java
> +    public static List<Integer> getUserInputlotto() throws IllegalArgumentException{
```suggestion
    public static List<Integer> getUserInputlotto() throws IllegalArgumentException {
```

2024-04-07 12:21 UTC, 3Juhwan commented on src/main/java/lotto/IO/input/InputHandler.java
> +    public static List<Integer> getUserInputlotto() throws IllegalArgumentException{
위에 언급한 Command+Option+L을 적용해 봐요!

2024-04-07 12:21 UTC, 3Juhwan commented on src/main/java/lotto/IO/input/InputHandler.java
> +    public static List<Integer> getUserInputlotto() throws IllegalArgumentException{
여기도 자바 메서드명 컨벤션을 참고해서 수정해 주세요!

2024-04-07 12:21 UTC, 3Juhwan commented on src/main/java/lotto/IO/input/InputHandler.java
> +    public static Integer getUserInputAmount() throws IllegalArgumentException{
`IllegalArgumentException`은 언체크 예외에요! 개발자에게 별도의 처리를 강제하지 않는 예외죠. `throws`으로 명시한 이유가 궁금하네요 💭

2024-04-07 12:21 UTC, 3Juhwan commented on src/main/java/lotto/IO/input/LottoInput.java
> +//        Info();
이미 알테지만 언급만 해둘게요 :) 사용하지 않는 클래스는 지워주세요!

2024-04-07 12:21 UTC, 3Juhwan commented on src/main/java/lotto/IO/input/LottoTicket.java
> +LottoTicket {
```suggestion
public class LottoTicket {
```

2024-04-07 12:21 UTC, 3Juhwan commented on src/main/java/lotto/IO/output/LottoOutput.java
> +import java.util.ArrayList;
```suggestion
```

2024-04-07 12:21 UTC, 3Juhwan commented on src/main/java/lotto/IO/output/LottoOutput.java
> +    public void PrintInfo() {
```suggestion
    public void printInfo() {
```

2024-04-07 12:21 UTC, 3Juhwan commented on src/main/java/lotto/IO/output/LottoOutput.java
> +    public void PrintLottos() {
```suggestion
    public void printLottos() {
```

2024-04-07 12:21 UTC, 3Juhwan commented on src/main/java/lotto/IO/output/RateOfReturnOutput.java
> +    public void Print() {
```suggestion
    public void print() {
```

2024-04-07 12:21 UTC, 3Juhwan commented on src/main/java/lotto/IO/output/WinOutput.java
> +    private final int[] WinPrice;
```suggestion
    private final int[] winPrice;
```

2024-04-07 12:21 UTC, 3Juhwan commented on src/main/java/lotto/IO/output/WinOutput.java
> +    public void Print() {
```suggestion
    public void print() {
```

2024-04-07 12:21 UTC, 3Juhwan commented on src/main/java/lotto/service/Win.java
> +    public void Count(List<Integer> wins, int bonus, List<List<Integer>> lottos) {
```suggestion
    public void count(List<Integer> wins, int bonus, List<List<Integer>> lottos) {
```

2024-04-07 12:21 UTC, 3Juhwan commented on src/main/java/lotto/Console.java
> +    }
사용하지 않는 메서드가 있네요!

2024-04-07 12:21 UTC, 3Juhwan commented on src/main/java/lotto/Console.java
> +    }
싱글톤으로 유지하는 것 좋네요 👍 
싱글톤의 장단점에 대해 알아볼까요?

2024-04-08 05:32 UTC, 2Jin1031 commented on src/main/java/lotto/IO/domain/Lotto.java
> +
`validate()`는 미션에 있던 메서드 그대로 가져오느라 인스턴스 메서드이고,
`numberRangeCheck()`는 그 안에서 코드를 짜다가 함수로 바꾸고 싶어서 인텔리제이 단축키를 눌렀더니 정적 메서드로  만들어졌어요.!
numbersRangeCheck()는 인스턴스 메서드로 쓰면 객체 생성하고 써야하는데 클래스 안에서만 쓸 거라..? 라고 추측해봐요

2024-04-08 05:50 UTC, 2Jin1031 commented on src/main/java/lotto/IO/input/InputHandler.java
> +    public static Integer getUserInputAmount() throws IllegalArgumentException{
덕분에 예외에는 체크 예외, 언체크 예외가 있다는 것을 알게되었어요!
예외 종류는 문제에서 명시한 그대로를 가져와 쓰고
try~catch 구문에서 예외를 반환하려면 try이 구문이 있는 곳으로 throws로 던져야 한다고 해서 
붙이고 코드 짜보니 원하는 대로 실행이 되길래 그대로 놔뒀던 것 같아요

예외에 대해 구글링을 해본 결과, 언체크 예외에서는 throws가 필수가 아니라고 해서
`throws IllegalArgumentException` 를 지우고 실행해봤더니 똑같이 catch가 잘 되는 군요!!
필요없는 명시라고 할 지라도 코드의 획일성을 위해 남겨놓는 것은 주로 쓰지 않는 코드 형식일까요??

2024-04-08 05:54 UTC, 2Jin1031 commented on src/main/java/lotto/Console.java
> +    }
console 버전에 문제가 있어서 잘 작동하는 console 코드를 그대로 가져오느라 쓰지 않는 메서드도 있는 것 같아요!
지원하는 console 라이브러리에서는 ReadOnly 형태여가지구 따로 변형시키지는 않았습니닷

2024-04-08 05:57 UTC, 2Jin1031 commented on src/main/java/lotto/Console.java
> +    }
이것도 그대로 코드를 가져온 거긴 하지만..!

싱글톤 장단점에 대해 알아보자면
싱글톤 사용시 메모리 낭비를 줄이는 장점이 있지만 유연성이 떨어지고 클라이언트가 구체 클래스에 의존한다는 단점이 있습니다ㅏ

2024-04-08 06:11 UTC, 2Jin1031 commented
> 이진님, 안녕하세요. 코드 잘 읽었어요!
> 
> 패키지 분리한 것이 인상 깊은 코드였어요. 코드를 읽으며 패키지를 분리한 의도가 궁금했어요. 질문하고 싶은 마음이 크지만, 이 부분은 일단 넘어갈게요.
> 
> 리뷰를 하며 중점을 둔 부분은 전반적인 포맷이에요. 코드 리뷰가 처음이니까, 차근차근 진행해 보려고 해요. 몇 가지 질문도 남겼으니 확인해 주세요! 15개 내외로 남긴다고 했는데, 하다 보니 많아졌네요 :)
> 
> 아, 그리고 변경 요청드린 부분을 반영하면서 커밋을 추가하게 될 텐데요. 커밋 단위를 현재보다 세세하게 하면 좋을 것 같아요. 하나의 커밋에 많은 변경 사항이 있으면 코드 추적이 쉽지 않답니다 😉 커밋 메시지에 prefix 잘 적용하고 계시네요 👍 세부 커밋 메시지를 영어로 작성했는데 의도가 있을까요?
> 
> 코멘트 확인 부탁드리고, 2차 리뷰 요청 마감 기한은 4/10(수)에요!


왕 섬세한 코드 리뷰 감사드립니다!!
저에게는 첫번째 코드 리뷰였는데 좋은 기억으로 남을 것 같아요:)

🤩오 이제 이모지 다는 법을 찾았습니다 `control + command + 스페이스` 이군요

아 말씀 대로 이번에는 좀 더 세세하게 커밋해보려고 했답니당

커밋 메시지를 영어로 작성한 이유는 여러 개가 있는데 
멋있어 보여서 이기도 하지만 😎
메서드나 변수명도 영어로 작성해야 하고 에러 메세지도 다 영어길래 커밋 메시지라도 영어로 작성해 좀 익숙해져볼까 했어요
처음에는 직접 치다가 시간 어택 때문에 chatGPT에게 요청해보다가
그렇게까지 도움은 안되는 것 같아서 
최근에는 한글로 작성하고 있는데
어떤 방식을 추천하시나요??

2024-04-08 10:00 UTC, 3Juhwan commented on src/main/java/lotto/IO/domain/Lotto.java
> +
```suggestion
    private void numbersRangeCheck(List<Integer> numbers) {
        for (int number : numbers) {
            if (number < 1 || number > 45) {
                throw new IllegalArgumentException("[ERROR] 로또 번호는 1부터 45 사이의 숫자여야 합니다.");
            }
        }
    }

```

이렇게 수정해 볼까요? 어플리케이션이 정상적으로 동작하나요?

2024-04-08 10:01 UTC, 3Juhwan commented on src/main/java/lotto/IO/domain/Lotto.java
> +
```suggestion
    private void validate(List<Integer> numbers) {
        numbersSizeCheck(numbers);
        numbersRangeCheck(numbers);
        numbersDuplicate(numbers);

    }

    private void numbersRangeCheck(List<Integer> numbers) {
        for (int number : numbers) {
            if (number < 1 || number > 45) {
                throw new IllegalArgumentException("[ERROR] 로또 번호는 1부터 45 사이의 숫자여야 합니다.");
            }
        }
    }

```

이렇게 변경해 볼까요? 어플리케이션이 정상적으로 동작하나요?

2024-04-08 10:02 UTC, 3Juhwan commented on src/main/java/lotto/IO/domain/Lotto.java
> +
```java
    private void numbersRangeCheck(List<Integer> numbers) {
        for (int number : numbers) {
            if (number < 1 || number > 45) {
                throw new IllegalArgumentException("[ERROR] 로또 번호는 1부터 45 사이의 숫자여야 합니다.");
            }
        }
    }

```
이렇게 수정해 볼까요? 어플리케이션이 정상적으로 동작하나요? 이유는 무엇일까요?

2024-04-08 10:09 UTC, 3Juhwan commented on src/main/java/lotto/IO/input/InputHandler.java
> +    public static Integer getUserInputAmount() throws IllegalArgumentException{
맞아요! 언체크 예외는 개발자에게 별도의 처리를 강제하지 않아요. `throws`, `try-catch`를 하지 않아도 되는 예외죠. 

> 필요없는 명시라고 할 지라도 코드의 획일성을 위해 남겨놓는 것은 주로 쓰지 않는 코드 형식일까요??

근거가 있네요 👍  저는 **획일성**을 대신에 **일관성**이라고 하는 데요. 일관성은 코드의 가독성에 있어 중요한 요소에요! 일관성을 위해 남겨 두는 것도 괜찮은 선택이에요. 

하지만 저는 남겨두는 근거로 충분하다고 생각하지 않아요. 예외 처리는 생각보다 신경 써야 할 게 많은 영역이에요. 그리고 `throws` 라는 키워드 하나로 생각보다 많은 의도를 담을 수 있어요. 현재는 일관성이라는 의도 밖에 없다면, 저라면 일관성 있게 `InputHandler` 내부 메서드의 붙은 모든 `throws`를 지울 것 같네요.

2024-04-08 10:13 UTC, 3Juhwan commented on src/main/java/lotto/Console.java
> +    }
아마도 우테코에서 제공하는 Console 라이브러리를 의미하는 것 같네요! 이번에 리뷰 요청한 코드에 여전히 해당 메서드가 남았는데 저라면 지울 것 같아요. 하지만 자세한 사항은 이진님이 더 잘 알 테니까 변경을 강제하진 않을게요! 이후 확장성을 고려했을 때, 필요할 수도 있겠어요.

2024-04-08 14:25 UTC, 3Juhwan requested changes
이진님, 안녕하세요! 제가 요청한 변경을 잘 적용해 주셨네요 👍 

이번에는 코멘트와 함께 여러 요구 사항을 제시해 드릴게요. 다음 프로그래밍 요구 사항을 충족한 코드를 완성해 주세요! 

- indent(인덴트, 들여쓰기) depth를 2를 넘지 않도록 구현한다. 1까지만 허용한다.
  - 예를 들어 while문 안에 if문이 있으면 들여쓰기는 2이다.
  - 힌트: indent(인덴트, 들여쓰기) depth를 줄이는 좋은 방법은 함수(또는 메서드)를 분리하면 된다.
- else 예약어를 쓰지 않는다.
  - else 예약어를 쓰지 말라고 하니 switch/case로 구현하는 경우가 있는데 switch/case도 허용하지 않는다.
  - 힌트: if문에서 값을 반환하는 방식으로 구현하면 else 예약어를 사용하지 않아도 된다.
- 함수(또는 메서드)의 길이가 10라인을 넘어가지 않도록 구현한다.
  - 함수(또는 메소드)가 한 가지 일만 하도록 최대한 작게 만들어라.
- 배열 대신 컬렉션을 사용한다.

그럼, 파이팅하세요!

2024-04-08 14:25 UTC, 3Juhwan commented on src/main/java/lotto/IO/domain/Lotto.java
> +
불필요한 개행이 남아 있네요!

2024-04-08 14:25 UTC, 3Juhwan commented on src/main/java/lotto/IO/domain/Lotto.java
> +        }
Stream으로 바꿔볼까요? for문과 비교하여 Stream이 갖는 장점은 무엇일까요?

2024-04-08 14:25 UTC, 3Juhwan commented on src/main/java/lotto/IO/domain/Lotto.java
> +    }
```suggestion
    private void numbersDuplicate(List<Integer> numbers) {
        if (numbers.stream().distinct().count() != 6) {
            throw new IllegalArgumentException("[ERROR] 로또 번호는 중복되지 않는 숫자여야 합니다.");
        }
    }
```

2024-04-08 14:25 UTC, 3Juhwan commented on src/main/java/lotto/IO/domain/Lotto.java
> +    }
Stream API는 많은 것을 지원해요!

2024-04-08 14:25 UTC, 3Juhwan commented on src/main/java/lotto/IO/domain/LottoNumberGenerator.java
> +    }
메서드 분리를 열심히 해주셨네요 👍 메서드 분리는 많은 이점을 갖고 있어요. `가독성`, `재사용성`, `테스트 용이`가 있죠. 이 부분은 다음 글을 참고하면 좋을 것 같아요! 
https://tecoble.techcourse.co.kr/post/2020-05-10-single-job-method/

다만, 저는 위 코드가 과하게 분리되어 있다고 생각해요! 이진님은 어떻게 생각하시나요? 세세하게 코드를 분석한 내용을 근거와 함께 제시해 주면 좋을 것 같아요.

2024-04-08 14:25 UTC, 3Juhwan commented on src/main/java/lotto/IO/domain/LottoRate.java
> +    }
이 부분도 동일해요. 저는 메서드로 분리하지 않아도 괜찮다고 생각하는데, 분리한 의도가 궁금하네요!

2024-04-08 14:25 UTC, 3Juhwan commented on src/main/java/lotto/IO/domain/Quantity.java
> + */
불필요한 주석은 지워주세요! 리뷰를 요청하는 경우에 지켜야 하는 기본적인 사항이에요 🙂

2024-04-08 14:25 UTC, 3Juhwan commented on src/main/java/lotto/IO/domain/Quantity.java
> +        this.quantity = (number) / 1000;
`LottoRate.class`와 다르게 계산이 생성자 내부에서 일어나고 있네요 :)
이런 부분이 `일관성이 깨진다`라고 할 수 있을 것 같아요.

2024-04-08 14:25 UTC, 3Juhwan commented on src/main/java/lotto/IO/domain/Quantity.java
> +    }
다음 글을 참고해서 클래스 내 메서드 순서를 수정해 주세요! 
https://engineerinsight.tistory.com/41

2024-04-08 14:25 UTC, 3Juhwan commented on src/main/java/lotto/IO/domain/Reward.java
> +    public Reward(int[] WinPrice, int[] correctCounts) {
```suggestion
    public Reward(int[] winPrice, int[] correctCounts) {
```
변수명 컨벤션을 지켜주세요!

2024-04-09 15:50 UTC, 2Jin1031 commented on src/main/java/lotto/IO/domain/Lotto.java
> +
정상적으로 동작합니다!
추측해보자면 이 메서드가 클래스의 static 필드를 사용하고 있는 게 없기 때문일까요..??

구글링 해본 결과 static 메서드는 객체지향을 해치고 인스턴스 변수를 직접적으로 사용할 수 없다고 나와있는데
이 이유 때문에 수정이 필요한 걸까요🥹 어떻게 검색해봐야 궁금증을 해결할 수 있을까요,,

2024-04-10 08:22 UTC, 2Jin1031 commented on src/main/java/lotto/IO/domain/LottoNumberGenerator.java
> +    }
사실 메서드를 기능에 따라 최대한 작게 분리하라 해서 그것만 생각하고 쪼개고 쪼개다보니 이런 코드가 나온 것 같아요
분리할 때 당시에는 `LottoNumberGenerator` 가 생성자인데 너무 긴게 어색하기도 하고 
생성도 하고 정렬하기도 하는 게 여러 기능을 가지고 있는 것 같아서 이처럼 분리했던 것 같습니다

이번에는 모두 지우고 generateLottoNumber 메서드만 추가해서 
하나의 Single 로또 번호를 생성하고 정렬하여 로또 번호 리스트를 반환시키는 분리 작업을 했는데요!
이 메서드이름을 정할 때는 Single이라는 단어가 중요한 지, Sort라는 단어가 중요한지, 아니면 다 넣은 메서드 이름이 좋을 지도 궁금합니다💭

2024-04-10 08:22 UTC, 2Jin1031 commented on src/main/java/lotto/IO/domain/LottoNumberGenerator.java
> +    }
사실 메서드를 기능에 따라 최대한 작게 분리하라 해서 그것만 생각하고 쪼개고 쪼개다보니 이런 코드가 나온 것 같아요
분리할 때 당시에는 `LottoNumberGenerator` 가 생성자인데 너무 긴게 어색하기도 하고 
생성도 하고 정렬하기도 하는 게 여러 기능을 가지고 있는 것 같아서 이처럼 분리했던 것 같습니다

이번에는 모두 지우고 generateLottoNumber 메서드만 추가해서 
하나의 Single 로또 번호를 생성하고 정렬하여 로또 번호 리스트를 반환시키는 분리 작업을 했는데요!
이 메서드이름을 정할 때는 Single이라는 단어가 중요한 지, Sort라는 단어가 중요한지, 아니면 다 넣은 메서드 이름이 좋을 지도 궁금합니다💭

2024-04-10 08:31 UTC, 2Jin1031 commented on src/main/java/lotto/IO/domain/LottoRate.java
> +    }
이 부분도 생성자가 긴 게 어색했던 것 같습니다,,
또 rate 라는 변수에 딱 결과값만 넣고 싶었던 바람도 있었던 것 같습니다만 아무리봐도 분리할만한 마땅한 근거가 없네요😂

2024-04-10 08:32 UTC, 2Jin1031 commented on src/main/java/lotto/IO/domain/Quantity.java
> + */
헉 네엡!

2024-04-11 11:11 UTC, 2Jin1031 commented on src/main/java/lotto/IO/domain/Lotto.java
> +        }
다양한 장점들이 있겠지만 코드의 간결성과 가독성 향상의 기능이 있습니다!

혹시 Stream으로 변경하실 때 인텔리제이에서 자동으로 완성해주는 기능을 사용하시나요 아님 Stream 문법에 대해 익히시고 사용하시는 지 궁금합니당

2024-04-11 12:36 UTC, 3Juhwan commented on src/main/java/lotto/IO/domain/Lotto.java
> +        }
장점에 대해 잘 알아 보셨네요 👍 

사실, Stream API는 단순히 반복문의 기능을 대체하는 정도가 아니에요. 함수형 프로그래밍이라는 패러다임을 자바에서 지원하기 위한 핵심 요소에요. 병렬 처리와 관련된 개념도 있고, 꽤 어려운 내용을 포함하고 있어요. 시간될 때 또는 흥미가 있다면 학습해 보는 것도 좋아요! 

> 혹시 Stream으로 변경하실 때 인텔리제이에서 자동으로 완성해 주는 기능을 사용하시나요 아님 Stream 문법에 대해 익히시고 사용하시는 지 궁금합니당

처음에는 자동 완성을 많이 사용했던 것 같아요. 익숙해질수록 그 비중이 줄어들더라고요! 그러다 언젠가 한 번 책을 읽은 적이 있죠. 이렇게 학습해도 놓치는 것도 분명 존재하죠. 지금은 전반적인 내용은 다 알지만 놓치는 건 구글링을 하는 것 같아요. 이진님만의 학습법으로 학습하는 것을 추천해요 :)

2024-04-12 15:30 UTC, 3Juhwan requested changes
이진님, 코드 잘 읽었어요. 제가 말씀드린 요구사항을 지키려는 노력이 보이네요 😄 

코멘트를 남기다 보니까 조금 많아졌어요. 제가 남긴 코멘트 외에도 리팩터링을 진행해 주세요! 더 수정할 부분을 못 찾으시겠나요? 제가 남긴 코멘트에서 힌트를 얻을 수 있을 거에요. 

추가로 다음 요구 사항을 충족해 주세요. 그리고 이 요구 사항을 반영하는 과정에서 파악한 의도를 알려주세요. 
- input과 output을 각각 하나의 클래스로 합친다. 즉 사용자 입력 받는 로직을 하나로, 콘솔에 출력하는 로직을 하나로 합쳐주세요. 
- package명과 분리한 방식을 고민하고 적절하게 수정해 주세요. 
- 클래스 명과 메서드 명을 적절하게 수정해 주세요. 
- getter를 지양해 주세요. 객체에게 메시지를 보내서 일하게 해주세요. 

다소 요구 사항이 많을 수 있겠어요. 사실, 모든 요구 사항을 만족하는 것은 매우 어렵고 때로 불가능할 수 있어요. 하지만 고민하는 과정에서 분명 얻는 것이 있을 거에요! 그리고 고민한 내용을 저에게 공유해 주면 좋을 것 같아요. 그럼 파이팅 하세요!

2024-04-12 15:30 UTC, 3Juhwan commented on src/main/java/lotto/IO/domain/Lotto.java
> +    public Lotto(List<Integer> numbers) {
이 부분에서 일관성이 깨졌네요! 다른 클래스와 비교해 볼까요?

2024-04-12 15:30 UTC, 3Juhwan commented on src/main/java/lotto/IO/output/Messages.java
> +public class Messages {
메세지를 한 곳에 모아두셨네요 👍 이렇게 하면서 어떤 장점이 있었나요?

2024-04-12 15:30 UTC, 3Juhwan commented on src/main/java/lotto/IO/domain/Lotto.java
> +        numbersDuplicate(numbers);
사소한 컨벤션이지만, 호출되는 순서와 메서드 선언 순서를 맞추는 것이 좋아요. 순서를 바꿔보는 건 어떤가요?

2024-04-12 15:30 UTC, 3Juhwan commented on src/main/java/lotto/IO/domain/Lotto.java
> +            throw new IllegalArgumentException();
이 부분에만 에러 메시지가 없는 이유가 무엇인가요?

2024-04-12 15:30 UTC, 3Juhwan commented on src/main/java/lotto/IO/domain/Lotto.java
> +        numbers.stream().mapToInt(number -> number).filter(number -> number < 1 || number > 45).forEach(number -> {
`forEach`를 사용할 때면 이 글을 읽어보는 것을 추천해요! 
https://tecoble.techcourse.co.kr/post/2020-05-14-foreach-vs-forloop/

2024-04-12 15:30 UTC, 3Juhwan commented on src/main/java/lotto/IO/domain/Lotto.java
> +        numbers.stream().mapToInt(number -> number).filter(number -> number < 1 || number > 45).forEach(number -> {
```suggestion
        numbers.stream()
            .mapToInt(number -> number)
            .filter(number -> number < 1 || number > 45)
            .forEach(number -> {
```

개행을 넣어서 가독성을 높여봐요!

2024-04-12 15:30 UTC, 3Juhwan commented on src/main/java/lotto/IO/domain/Lotto.java
> +        if (numbers.stream().distinct().count() != 6) {
이 부분, 제가 언급한 대로 수정하셨네요! 한가지 더 말씀드리고 싶은 게 있어요. 
`numbers.stream().distinct().count()`가 과연 가독성 좋은 코드일까요?

2024-04-12 15:30 UTC, 3Juhwan commented on src/main/java/lotto/IO/domain/LottoRate.java
> +public class LottoRate {
개인적으로 클래스의 역할과 클래스 명이 와닿지 않네요!

2024-04-12 15:30 UTC, 3Juhwan commented on src/main/java/lotto/IO/domain/Quantity.java
> +        if ((number < 0)) {
```suggestion
        if (number < 0) {
```

2024-04-12 15:30 UTC, 3Juhwan commented on src/main/java/lotto/IO/domain/Quantity.java
> +        if ((number % 1000) != 0) {
```suggestion
        if (number % 1000 != 0) {
```

2024-04-12 15:30 UTC, 3Juhwan commented on src/main/java/lotto/IO/domain/Quantity.java
> +    private static void validateAmountInThousandUnites(int number) {
`static`을 지워볼까요?

2024-04-12 15:30 UTC, 3Juhwan commented on src/main/java/lotto/IO/domain/Reward.java
> +        this.reward = IntStream.range(0, winPrice.toArray().length).map(i -> winPrice.get(i) * correctCounts.get(i)).sum();
```suggestion
        this.reward = IntStream.range(0, winPrice.toArray().length)
            .map(i -> winPrice.get(i) * correctCounts.get(i))
            .sum();
```

2024-04-12 15:30 UTC, 3Juhwan commented on src/main/java/lotto/IO/info/Info.java
> +}
이 클래스가 담당하고 있는 역할이 많이 적어 보이네요! 다른 클래스로 옮기고, 이 클래스는 지울 수 없을까요?

2024-04-12 15:30 UTC, 3Juhwan commented on src/main/java/lotto/IO/domain/Lotto.java
> +        numbersDuplicate(numbers);
이 클래스 뿐만 아니라 다른 클래스도 동일하네요!

2024-04-12 15:30 UTC, 3Juhwan commented on src/main/java/lotto/IO/output/LottoOutput.java
> +public class LottoOutput {
<img width="412" alt="스크린샷 2024-04-12 오후 6 50 22" src="https://github.com/2Jin1031/java-lotto/assets/64410384/c7b261df-2096-406d-825d-f0aaa19d6953">

사용자를 위해 예외 메시지를 수정해 주세요!

2024-04-12 15:30 UTC, 3Juhwan commented on src/main/java/lotto/IO/input/Bonus.java
> +    }
```suggestion
    private void numberRangeCheck(int bonus) {
        if (bonus < 1 || bonus > 45) {
            throw new IllegalArgumentException(Messages.BONUS_RANGE_ERROR);
        }
    }

    private void duplicateByLotto(int bonus, Lotto lotto) {
        List<Integer> numbers = lotto.getNumbers();
        if (numbers.contains(bonus)) {
            throw new IllegalArgumentException(Messages.BONUS_DUPLICATE_ERROR);
        }
    }
```

2024-04-12 15:30 UTC, 3Juhwan commented on src/main/java/lotto/LottoGame.java
> +public class LottoGame {
요구사항에 맞춰 메서드 분리가 잘 됐네요 👍

2024-04-12 15:30 UTC, 3Juhwan commented on src/main/java/lotto/LottoGame.java
> +        LottoTicket lottoTicket = UserInputErrorManager.checkAmount();
클래스 명과 메서드 명 등의 표현이 어색하게 느껴지네요! 해당 라인을 읽고 든 생각은 다음과 같아요. 

- `UserInputErrorManager`: 사용자 입력에 오류가 있는지 검사하는 역할을 하지 않을까? 
- `UserInputErrorManager.checkAmount()`: Amount를 검사하려고 하는데 파라미터가 없네?
- `LottoTicket lottoTicket = UserInputErrorManager.checkAmount();`: Amount를 검사하는 메서드라고 생각했는데 LottoTicket이 반환되네? 

메서드나 클래스가 생각보다 많은 책임을 갖는 것 같단 생각도 드네요! 적절하게 네이밍을 수정하거나, 분리해 보면 좋을 것 같아요 😀

2024-04-12 15:30 UTC, 3Juhwan commented on src/main/java/lotto/LottoGame.java
> +        LottosGenerator lottosGenerator = new LottosGenerator(quantity.getQuantity());
`LottosGenerator`의 생성자에 `Quantity`를 넘기는 코드로 변경해 볼래요? getter 대신에 객체에게 메시지를 보내는 OOP를 학습하는 좋은 기회가 될 것 같네요 😀 

https://tecoble.techcourse.co.kr/post/2020-04-28-ask-instead-of-getter/

2024-04-12 15:30 UTC, 3Juhwan commented on src/main/java/lotto/IO/output/WinOutput.java
> +import java.util.ArrayList;
안 쓰는 import가 있네요!

2024-04-12 15:30 UTC, 3Juhwan commented on src/main/java/lotto/IO/output/MessagePrinter.java
> +public interface MessagePrinter {
interface로 분리해 주셨네요! 어떤 장점이 있었나요?

2024-04-12 15:40 UTC, 3Juhwan commented on src/main/java/lotto/IO/domain/LottoNumberGenerator.java
> +    }
우선, 이번에 변경된 코드가 읽기 좋은 것 같네요! 

> 이 메서드이름을 정할 때는 Single이라는 단어가 중요한 지, Sort라는 단어가 중요한지, 아니면 다 넣은 메서드 이름이 좋을 지도 궁금합니다. 

범용적인 이름과 세부적인 이름 사이의 고민인 것 같네요. 메서드가 다소 길어지더라도 세부적인 이름을 사용하라는 문구를 많이 읽은 것 같아요. 이 의견에 동의는 하지만 범용적인 이름을 좀더 선호하는 데요. 저는 메서드명이 매우 길어지는 것을 좋아하지 않아요. 또한, 메서드명에 세부 구현에 대한 내용이 포함되면 캡슐화가 깨진다고 생각해요. 

현재 코드는 `generateLottoNumber()`라는 이름을 사용해요. 제가 이진님의 동료 개발자고, 미션을 같이 진행한다고 가정해 볼게요. 저는 `generateLottoNumber()`를 사용하면서 세부 구현은 궁금하지 않아요. 로또 번호를 생성하는 데에 관심이 있지, 어떻게 생성되는 지는 궁금하지 않아요. 만약 메서드 명이 `Sorted`, `Single`을 포함한 `generatSingleSortedLottoNumber()`라면 오히려 가독성이 떨어질 것 같아요. 

하지만 상황에 따라 다르답니다. 개발은 고민의 연속이고 적절한 선택을 하는 것이 잘하는 개발자라고 생각해요!

2024-04-14 14:50 UTC, 2Jin1031 commented
주환님! 세세한 리뷰 감사합니다!!

> * input과 output을 각각 하나의 클래스로 합친다. 즉 사용자 입력 받는 로직을 하나로, 콘솔에 출력하는 로직을 하나로 합쳐주세요.
> * package명과 분리한 방식을 고민하고 적절하게 수정해 주세요.
> * 클래스 명과 메서드 명을 적절하게 수정해 주세요.
> * getter를 지양해 주세요. 객체에게 메시지를 보내서 일하게 해주세요.

이번 코드리뷰는 정말 머리를 쥐어뜯으면서 리펙토링을 했어요😇
그만큼 보완해야 할 부분을 잘 짚어주셨다는 뜻이겠죠??  덕분에 한 층 더 성장하는 기회가 된 것 같아 감사한 마음이 큽니다!

> 다소 요구 사항이 많을 수 있겠어요. 사실, 모든 요구 사항을 만족하는 것은 매우 어렵고 때로 불가능할 수 있어요. 하지만 고민하는 과정에서 분명 얻는 것이 있을 거에요! 그리고 고민한 내용을 저에게 공유해 주면 좋을 것 같아요. 그럼 파이팅 하세요!

2024-04-14 15:41 UTC, 2Jin1031 commented on src/main/java/lotto/IO/output/MessagePrinter.java
> +public interface MessagePrinter {
Message 문구들이 흩어져 있어서 한 곳으로 정리해주고 싶었는데
이 때 바로 생각난 것이 interface였어서 사용해봤는데 유연성과 확장성에 도움이 되는 장점이 있었습니다
나중에 message 출력에 대한 요구사항이 변경된다면 이전보다 더 수월하게 유지보수 할 수 있을 것 같아요👍

2024-04-14 15:46 UTC, 2Jin1031 commented on src/main/java/lotto/LottoGame.java
> +        LottoTicket lottoTicket = UserInputErrorManager.checkAmount();
아 생각을 풀어서 써주셔서 덕분에 어떤 생각의 흐름을 가지고 코드를 보셨는지 이해가 잘 되었어요 👍
특히 
> * `UserInputErrorManager.checkAmount()`: Amount를 검사하려고 하는데 파라미터가 없네?
이 부분에서 아 뭔가 객체지향스럽지 않음이 확 느껴져서 이번에 코드 수정 작업을 할 때 Input을 메서드 안에서 받아서 검사까지 하는게 아니라 인자로 받는 방식으로 수정해보려고 했어요!

메서드 명에 check라는 단어가 그리 직관적으로 역할을 보여주지 못한다는 생각도 함께 들어서 이번에는 parseInt, valid 등 명확한 표현을 쓰려고 노력했습니다😊

2024-04-14 15:50 UTC, 2Jin1031 commented on src/main/java/lotto/IO/domain/LottoRate.java
> +public class LottoRate {
처음에 이 네임명을 정할 때 로또 수익률 관련해서 파파고에 돌려봤더니 rate of return이 나오길래
아 한단어로 짓고 싶은데.. 라는 생각으로 rate로 지었던 것 같아요
LottoRate만 보면 로또비율,, 로또율 고민하게 되네요

이번에는 RateOfReturn으로 변경해봤는데 아직까지도 고민이 명확히 해결되지는 않았어요
ReturnRate, RateReturn, Profit 등 후보들이 머리속에서 돌고 있습니다🙃
이렇게 여러 단어들의 결합으로 이루어져있다면 주환님이라면 어떻게 네이밍 방식을 고민하시고 정하셨을 지 궁금합니다!

2024-04-15 04:58 UTC, 2Jin1031 commented on src/main/java/lotto/IO/info/Info.java
> +}
OutputService class 내의 WinStatistics 이라는 메서드에 당첨 통계에 대한 내용을 다 통합해봤습니다!

2024-04-15 05:04 UTC, 2Jin1031 commented on src/main/java/lotto/IO/domain/Lotto.java
> +            throw new IllegalArgumentException();
앗,, 실수로 놓쳤던 것 같아요
실행시켜보면서 로또 갯수에 대해서는 예외 상황을 안 만들어서 미쳐 확인하지 못한 채 제출했네요ㅜ
수정 완료했습니다!

2024-04-15 05:05 UTC, 2Jin1031 commented on src/main/java/lotto/IO/output/Messages.java
> +public class Messages {
메세지 관련 유지 보수가 수월해집니다!
메시지를 찾으러 여러 클래스들 사이를 안 돌아다녀도 되어서 편했어요

2024-04-15 06:13 UTC, 2Jin1031 commented on src/main/java/lotto/IO/domain/Lotto.java
> +        if (numbers.stream().distinct().count() != 6) {
아 사실 stream을 처음 접했을 때 이것저것 찾아보다가 
축약 형태가 많은 stream 형식에 대해 모든 개발자가 익숙하리라는 보장이 없기 때문에 
협업이 중요한 분야인 만큼 for문의 형태를 그대로 살리는 방식이 가독성이 더 좋은 방식이 될 수 있다라는 글을 본 적이 있었어요.

그 이후로 stream을 알고 쓰는게 아니라 자동완성으로 바꾸기만 할 거라면 
코드를 짜면서 그리고 유지보수 하기도 쉽도록 stream 보다는 기본 문법을 사용하려고 했는데요.

> 사실, Stream API는 단순히 반복문의 기능을 대체하는 정도가 아니에요. 함수형 프로그래밍이라는 패러다임을 자바에서 지원하기 위한 핵심 요소에요. 병렬 처리와 관련된 개념도 있고, 꽤 어려운 내용을 포함하고 있어요. 시간될 때 또는 흥미가 있다면 학습해 보는 것도 좋아요!

하지만 코드 리뷰를 진행하면서 stream API는 반복문 대체 외에도 다양한 기능들을 포함하고 있기에 
코드 형식만 가지고 판단 할 것이 아니라는 생각도 들었습니다.

> 이 부분, 제가 언급한 대로 수정하셨네요! 한가지 더 말씀드리고 싶은 게 있어요. `numbers.stream().distinct().count()`가 과연 가독성 좋은 코드일까요?

이번에는 스트림 형식보다 HashSet 형태로 확인하는 것이 좀 더 가독성과 직관성을 챙길 수 있을 것 같아서 수정해보았습니다.

2024-04-15 07:36 UTC, 2Jin1031 commented on src/main/java/lotto/LottoGame.java
> +        LottosGenerator lottosGenerator = new LottosGenerator(quantity.getQuantity());
링크 글 잘 읽었습니다. 예시 코드가 아주 탐나는 군요

제 스스로 변경 해봤습니다.. 만
getQuantity를 LottoGenerator에서 쓰고 싶지 않았는데
고쳐도 고쳐도 원하는 대로 수정이 안되어서
이 부분에 대해 조언을 듣고 싶습니다🫠

2024-04-17 14:45 UTC, 3Juhwan approved these changes
요구 사항을 반영하느라 정말 고생 많았어요 🎉🎉🎉

코드가 참 예뻐졌네요. 시간이 된다면 첫 PR을 요청한 시점의 코드와 현재 코드를 비교해 보면 좋을 것 같아요. 느끼는 차이만큼 성장했다고 생각해요. 

저 또한 많은 걸 느끼고 배웠어요. 리뷰를 하면서 모든 과정 속에 의도를 담았어요. 남겨준 피드백을 보니 제가 의도한 대로 진행된 부분이 있어서 개인적으로 뿌듯하네요. 하지만, 부족한 부분이 있어서 아쉽기도 하고요. 리뷰어로서 많이 부족한 역량과 자질을 갖고 있음에도 끝까지 열정적으로 참여해 줘서 고마워요. 

1주일이라는 짧은 시간이었지만, 성장에 도움이 되는 시간이었으면 좋겠네요. 오늘 우테코에서 들었던 말 중 크게 공감한 말을 공유하면서 마무리 해볼게요. 
_경험은 사람에게 일어나는 일이 아니라 일어나는 일에 대해 사람이 하는 행동이다._ 

시험 기간이기도 하고, 현재 시점에서 코드가 꽤 괜찮아서 코멘트는 아주 조금 남겼어요! 욕심이 난다면 mvc 패턴을 학습하고 코드에 적용해 보아도 좋을 것 같아요. 언제든 궁금한 점이 생기면 언제든 연락 주세요. 

> 로또 당첨통계를 출력하면서 5개 일치, 보너스 볼 일치 이 부분 때문에 처리가 복잡해 보입니다. 이 부분을 깔끔하게 처리할 방법에 대해 주환님의 의견이 궁금합니다.

좀더 구체적으로 질문해주면 좋을 것 같아요. 어떻게 복잡한 건지, 왜 복잡하다고 생각하는지, 어떤 고민을 했는지 등을 공유해 주면 리뷰어도 더 도움을 줄 수 있어요! 

> 클래스명과 필드명이 같은 상황이 다소 있었어요. 예로 Quantity class를 들면, 필드도 quantity에, getQuantity 메서드도 있어 quantity.getQuantity() 와 같이 중복되는 부분이 있는데 이를 개선할 좋은 방법에 대해 조언을 구하고 싶습니다., 단어가 겹치는 것을 방지하기 위해 필드명을 number로 수정하는게 좋을 지 아니면 중복되더라도 확실한 네이밍인 quantity를 사용하는 게 좋을 지 중에 고민하고 있습니다. 

좋은 고민이에요! 현재 `Quantity`는 원시값을 포장한 클래스로 보이네요. 맞아요. `quantity.getQuantity()`는 어색해요. VO(value object)나 원시값을 포장하는 클래스 또는 Record class를 사용하는 경우에 발생하는 고민이에요. 
저는 클래스 명과 필드를 다르게 작성하려 해요. `Quantity.class`를 예로 들면, `quantity`라는 필드명 대신에 `number`은 어떤가요? 생성자 파라미터에 number을 사용했던데 필드명으로 그대로 사용해도 괜찮을 것 같아요. 

> 추가적으로, 필드를 그대로 가져오는 `getQuantity()`는 `get()`으로 변경하는 것은 어떻게 생각하시는지도 궁금합니다.

저는 강력하게 안된다고 생각해요! getter, setter 등의 메서드명은 자바 개발자에게 널리 퍼진 컨벤션이에요. 뿐만 아니라 자바의 많은 프레임워크와 라이브러리는 getter 역할의 메서드가 getXX의 컨벤션을 따른다고 가정하고 동작해요. 이 컨벤션을 어긴다면 큰 문제가 발생할 것 같네요! 

> input과 output을 하나로 합치라는 요구사항을 지키다보니 output 패키지에는 클래스가 하나만 남게되어 패키지의 필요성에 대해 고민 중입니다. input 패키지와 일관성을 위해서라도 output 패키지를 삭제하지 않는 게 좋을까요?

저라면 `input` 패키지와 `output` 패키지를 합칠 것 같아요. 그리고 추후에 mvc 패턴을 공부하고 코드에 적용해 본다면 정답을 찾을 수 있을 거예요. 

> static 사용의 지양을 하기 위해서 다른 클래스들의 static은 모두 삭제 했지만 InputHandler, InputValidator 에 있는 static은 연결 되어 있기도 하고, 계속 인스턴스로 호출하는 것보다 정적으로 호출하는 게 더 나아보이는 것 같기도 한데, static 사용이 타당한지 여전히 확신이 서지 않습니다. 이에 대한 견해가 필요합니다.

`static 메서드`를 지향해야 하는가에 대해 많이 고민하고 팀원들과 토의해 봤지만 결론을 내지 못했답니다. 결정적인 장점 또는 단점을 찾지 못했어요. 그렇다면 컨벤션의 영역이라는 생각이 드네요. static 메서드와 인스턴스 메서드의 차이를 명확히 구분하고, 어느 경우에 어떤 메서드를 사용하는 것이 적절한 지 이진님만의 컨벤션을 정해보는 것은 어떤가요? 
제 개인적인 생각으로 `InputHandler.class` 등의 클래스 내부 메서드는 static이어도 괜찮다고 생각해요. 다만, 이전에 생성자에서 호출하는 `validateXX()` 같은 메서드는 인스턴스 메서드가 적절하다고 생각해요! 


> 기간 내에 굴러가는 코드를 만들어야 하니, 객체지향을 지키기는 커녕 메서드 내에 코드가 20줄 정도 됐던 채로 제출했던 게 마음에 걸렸습니다. 

사실, 잘한 거에요. 개발은 기한이 정해진 작업이에요. 기한 안에 굴러가는 코드를 완성하는 것이 최우선이예요. 예를 들어, 학교 수업에 과제를 제출해야 해요. 하지만 기한 안에 퀄리티 있는 과제를 수행하기 어려운 상황이라고 하면 어떤 선택을 해야 할까요? 어떻게든 끝내고 기한 안에 제출하는 선택이 최선이겠죠. 0점 받는 것보단 나으니깐요. 
이 예시에서 학교 과제를 개발 업무로 치환하면, 그 무게감은 다를 거에요. 우테코에서 유명한 말인데, **돌아가는 쓰레기를 만들어라**. 이 측면에서 이진님은 바람직한 선택을 했다고 생각해요. 개발뿐만 아니라, 인생 전반에서 우리는 항상 고민하지 않나요? 시간은 한정되어 있고, 하고 싶은 건 많잖아요! 우리는 적절한 trade-off가 필요해요. 이것을 잘하는 것이 잘하는 개발자라고 생각하고, 인생을 잘 사는 것 같단 생각을 한답니다.

2024-04-17 14:45 UTC, 3Juhwan commented on src/main/java/lotto/LottoGame.java
> +        LottoTicket lottoTicket = InputValidator.getValidLottoTicket();
열심히 고민하고 작성한 흔적이 보이네요! 꽤 예쁜 코드가 된 것 같아요. `LottoGame` 클래스의 모양이 전반적으로 마음에 들어요. 
하지만 저에게는 아직 클래스 명이 애매하게 느껴지네요. `InputValidator`라고 하면, 어떤 입력 값을 검증하는 클래스라고 생각돼요. 하지만 이 클래스는 사용자에게 직접 입력을 받고, 값을 검증하는 역할을 하고 있죠. 
현재 코드에서 변경한다면 `InputValidator` 보다는 `UserInput` 정도가 괜찮을 것 같아요. 이후, mvc 패턴을 적용한다면 `InputView`가 가장 적절할 것 같아요.

2024-04-17 14:45 UTC, 3Juhwan commented on src/main/java/lotto/LottoGame.java
> +        LottosGenerator lottosGenerator = new LottosGenerator(quantity);
`LottosGenerator`라는 클래스 명도 명확하지 않다고 생각해요! 저는 `LottosGenerator` 보다는 `Lottos` 가 명확하다고 생각해요.

2024-04-17 14:45 UTC, 3Juhwan commented on src/main/java/lotto/IO/domain/Bonus.java
> +    }
```suggestion
    private void numberRangeCheck(int bonus) {
        if (ConfigConstants.LOTTO_MIN_NUMBER > bonus || bonus > ConfigConstants.LOTTO_MAX_NUMBER) {
            throw new IllegalArgumentException(PromptConstants.BONUS_RANGE_ERROR);
        }
    }
```

정말 미세한 팁이에요!

2024-04-17 14:45 UTC, 3Juhwan commented on src/main/java/lotto/IO/domain/Win.java
> +        IntStream.range(0, 8).forEach(i -> correctCounts.add(0));
```suggestion
        this.correctCounts = new ArrayList<>(Collections.nCopies(8, 0));
        this.winPrices = List.of(0, 0, 0, 5000, 50000, 1500000, 30000000, 2000000000);
```

2024-04-17 14:45 UTC, 3Juhwan commented on src/main/java/lotto/IO/domain/Win.java
> +    }
그래도 개행을 넣어주는 게 좋은 것 같아요.

2024-04-17 14:45 UTC, 3Juhwan commented on src/main/java/lotto/IO/domain/LottosGenerator.java
> +    }
```suggestion
    private List<List<Integer>> generateLottos(Quantity quantity) {
        int numLottos = quantity.getQuantity();
    return IntStream.range(0, numLottos)
                    .mapToObj(i -> generateLottoNumber())
                    .collect(Collectors.toList());
    }
```

2024-04-17 14:45 UTC, 3Juhwan commented on src/main/java/lotto/IO/domain/LottosGenerator.java
> +    public List<Integer> generateLottoNumber() {
메서드 사이에 개행을 추가해 주세요!

2024-04-17 14:45 UTC, 3Juhwan commented on src/main/java/lotto/IO/input/InputValidator.java
> +}
Supplier는 java가 제공하는 클래스에요! 재정의한 이유가 있을까요?

2024-04-27 09:25 UTC, 2Jin1031 commented on src/main/java/lotto/IO/input/InputValidator.java
> +}
헙.. 고민해봤는데 이유가 없는 것 같아... 
삭제하는 리펙토링을 진행했습니다.!

2024-04-27 09:57 UTC, 2Jin1031 commented
감사합니다! 덕분에 마지막까지 좋은 팁들 얻어갈 수 있었던 것 같아요 👍



> > 로또 당첨통계를 출력하면서 5개 일치, 보너스 볼 일치 이 부분 때문에 처리가 복잡해 보입니다. 이 부분을 깔끔하게 처리할 방법에 대해 주환님의 의견이 궁금합니다.
> 
> 좀더 구체적으로 질문해주면 좋을 것 같아요. 어떻게 복잡한 건지, 왜 복잡하다고 생각하는지, 어떤 고민을 했는지 등을 공유해 주면 리뷰어도 더 도움을 줄 수 있어요!

아 코멘트가 너무 길어지는 것 같아서 조금 깔끔하게 작성해보려고 수정했더니 중요한 부분을 다 날린 것 같네요😂

로또 당첨 통계의 경우
일치하는 내역을 3개 부터 5개까지는 출력문구도 일관성있는 규칙성이 있는데 5개 + 보너스 부분에서는 출력 부분이 갑자기 달라져서 고민이 생겼던 것 같아요.
리스트로 winPrice와 correctCounts를 인덱스랑 맞춰서 일관성있게 출력하고 싶어서
winPrices 리스트 형식도 `List.of(0, 0, 0, 5000, 50000, 1500000, 30000000, 2000000000);` 이렇게 만들었어요. 
(사실 이방법도 좋은 코드인지 의구심이 들기는 합니다 ㅎ..ㅎ)

correctCounts 리스트는 set의 idx 부분이 result로 일관이었으면 좋겠어서 코드를 짜다보니
<img width="503" alt="스크린샷 2024-04-27 오후 6 50 14" src="https://github.com/2Jin1031/java-lotto/assets/111180367/4eaf67cb-5683-4e7c-8b4b-9036c319f6ad">
 `5개 + 보너스 부분`은 인덱스 7로 되더라구요,,

<br>
<img width="1014" alt="스크린샷 2024-04-27 오후 6 52 08" src="https://github.com/2Jin1031/java-lotto/assets/111180367/c56fb78c-5618-4796-b95e-84b191c1bb53">
그래서 출력 부분을 보면 
`5개 + 보너스 부분` : winPrices.get(6)과 correctCounts.get(7)을 사용하고
'6개' : winPrices.get(7)과 correctCounts.get(6)을 사용하는
다소 깔끔하지 못한 로직이 되는 것 같아서
주환님이라면 어떤 방법을 고민하셨을 지 궁금합니다!

2024-05-01 15:55 UTC, merged